Some weights of CausalBert were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['Q_cls.0.2.weight', 'g_cls.weight', 'Q_cls.1.2.bias', 'Q_cls.1.2.weight', 'Q_cls.1.0.bias', 'Q_cls.0.0.weight', 'g_cls.bias', 'Q_cls.1.0.weight', 'Q_cls.0.2.bias', 'Q_cls.0.0.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "CausalBertInference.py", line 10, in <module>
    cb.eval()
AttributeError: 'CausalBertWrapper' object has no attribute 'eval'
